---

- name: Copy the keys to the strongswan directory
  copy:
    content: "{{ item.content }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - content: "{{ keymanager.result.ca_cert }}"
      dest: "{{ config_prefix|default('/') }}etc/ipsec.d/cacerts/ca.crt"
      owner: strongswan
      group: "{{ root_group|default('root') }}"
      mode: "0600"
    - content: "{{ keymanager.result.server.certificate }}"
      dest: "{{ config_prefix|default('/') }}etc/ipsec.d/certs/{{ remote_host }}.crt"
      owner: strongswan
      group: "{{ root_group|default('root') }}"
      mode: "0600"
    - content: "{{ keymanager.result.server.private_key }}"
      dest: "{{ config_prefix|default('/') }}etc/ipsec.d/private/{{ remote_host }}.key"
      owner: strongswan
      group: "{{ root_group|default('root') }}"
      mode: "0600"
  notify:
    - restart strongswan
